#!/bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi

set -e

unset RM
unset MAKEFLAGS

./autogen.sh --prefix="$SPKG_LOCAL" --with-boost=$SPKG_LOCAL --with-python
make
make install
