#!/bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi

set -e

unset RM
unset MAKEFLAGS

./configure --prefix="$SPKG_LOCAL"
make
make install
